spring:
  application:
    name: bookstore

  lifecycle:
    timeout-per-shutdown-phase: 30s

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always
      continue-on-error: true

  datasource:
    url: jdbc:mysql://133.186.241.167:3306/project_be7_2joping_dev
    username: be7_2joping
    password: WF.2!2CuQm_g7HB0
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: 133.186.241.167
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 111

server:
  port: 8084
  shutdown: graceful

logging:
  level:
    root: WARN

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    instance-info-replication-interval-seconds: 30
    service-url:
      defaultZone: http://admin:1234@133.186.132.193:8761/eureka
  instance:
    prefer-ip-address: true

management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    pause:
      enabled: true
    resume:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

mysql-info:
  url: ba2840131e234a95a46d99ac7e17f43d
  username: 8ae6c33e9b69482abecf5f40c276487f
  password: af00bb3fd6ab4e2bb928546a31d43682

keymanager:
  appkey: 500rMJPT021TnyNl
  url: https://api-keymanager.nhncloudservice.com/keymanager/v1.2
  access-key-id: xbDehDmJgqDqjjLXa7Rl
  secret-access-key: 1knhNA219Vu5ak8Y
